package modelo;

import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.DAOGatitos;

/**
 * Gatitos generated by hbm2java
 */
@Entity
@Table(name="gatitos")
public class Gatitos implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
	@Column(name = "id",unique=true)
	private Integer id;
	@Column(name = "nombre")
	private String nombre;
	@Column(name = "raza")
	private String raza;
	@Column(name = "edad")
	private int edad;
	@Column(name = "foto")
	private String foto;

	public Gatitos() {
	}
	
	public Gatitos(Integer id, String nombre, String raza, int edad, String foto) {
		this.id=id;
		this.nombre = nombre;
		this.raza = raza;
		this.edad = edad;
		this.foto = foto;
	}

	public Gatitos(String nombre, String raza, int edad, String foto) {
		this.nombre = nombre;
		this.raza = raza;
		this.edad = edad;
		this.foto = foto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
	
	public void insertar() {
		DAOGatitos.insertar(this);
	}

	public void borrar() {
		DAOGatitos.borrar(this);
	}

	public List<Gatitos> listarGatitos() {
		List lista = null;

		lista = DAOGatitos.listarGatitos();

		return lista;
	}

	public void buscarID(int id) {
		Gatitos e = null;
		e = DAOGatitos.buscar(id);
		if (e != null) {
			this.id = e.getId();
			this.nombre = e.getNombre();
			this.raza = e.getRaza();
			this.edad = e.getEdad();
			this.foto = e.getFoto();
		}
	}

	public void actualizar() {
		DAOGatitos.actualizar(this);
	}

}
